theme: minima
title: My First Test Site
author: DeepBlueBW
email: deepbluebw@gmx.net
description: > # this means to ignore newlines until "baseurl:"
  It's the first try of a homepage.
  Let's have a look how it goes.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  DeepBlueBW # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
